services:
  om_code_db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - om_code_db-data:/var/lib/postgresql/data

  om_code_backend:
    build: ./backend
    container_name: om_code_backend
    environment:
      DATABASE_URL: postgres://user:password@om_code_db:5432/mydatabase
    ports:
      - "3300:3300"
    depends_on:
      - om_code_db

  om_code_frontend:
    build: ./frontend
    container_name: om_code_frontend
    ports:
      - "5173:5173"
    depends_on:
      - om_code_backend

volumes:
  om_code_db-data:
