services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend
    environment:
      DATABASE_URL: postgres://user:password@db:5432/mydatabase
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:3000"
    depends_on:
      - backend

volumes:
  db-data:
